### ISSUE TITLE
High Level building blocks missing from Challenge 1- makes deploying proxy script difficult to use

### ISSUE THREAD

**Issue by kamoclav** [microsoft/openhack-mc4h#67]
In Challenge 1 we have scripts to deploy the fhir api (and service client) and proxy which is awesome.  The issue is it's not very clear we are setting up a service client app registration so when we start asking for the tenant id and other service client info for the deploy proxy script it would be difficult to know where to go if you aren't already familiar with the architecture or have prior knowledge to draw from.

![image](https://user-images.githubusercontent.com/78386846/143900132-020503f2-ed51-4751-8578-91b789ed7566.png)

Since partners will specialize in different areas and may not be azure ad experts we should give a high level image of the architecture or guide them to the service client a little more.

Also does github really not allow issue linking to the actual files or code? : (

https://github.com/microsoft/openhack-mc4h/tree/main/Challenge-01

**Comment by daemel** [comment]
Interesting comment.  we have high level of architectures to add, but an additional step would be to simply add that as a reference in the KV that we would read in during the proxy.  

For Training it may be best to default everyone to MSI to limit the amount of SP's we create.  

I will code and test both approaches, but lets discuss the architecture diagram to add and where it should go. 

on the second question, you can launch an issue from code in github, just use the github browser... here is a link with the step by step: https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-code
