### ISSUE TITLE
Keyvault default in Proxy deployment script doesn't match what the fhir deployment script deploys

### ISSUE THREAD

**Issue by kamoclav** [microsoft/openhack-mc4h#68]
If a learner uses the defaults in the proxy deployment script they will not be successful deploying it. The keyvault default includes a prefix that was not added to the name of the keyvault deployed by the fhir deployment script.

![image](https://user-images.githubusercontent.com/78386846/143908637-a9a59248-5c78-4e08-9731-bd59499df9a9.png)

We should either change the fhir service deployment script to add the prefix or remove it from the proxy script deployment default.

**Comment by daemel** [comment]
I will remove it from Proxy - thanks @kamoclav
