### ISSUE TITLE
Fhir Proxy deployment script is not generating a postman environment Json

### ISSUE THREAD

**Issue by kamoclav** [microsoft/openhack-mc4h#69]
In Challenge 1 we have folks use a script to deploy the fhir proxy then ask them to download the postman environment json to create the environment for connecting to the proxy. 

Problem is, the proxy deployment script doesn't create the environment json file
![image](https://user-images.githubusercontent.com/78386846/143916617-6c348b3d-7e58-4b4b-8b13-870b455c8253.png)

It is also not updating the original environment file if that was the goal.

Recommended fix: The Fhir proxy script should generate a postman environment file.

**Comment by kamoclav** [comment]
Doesn't look like there is a decision point in this script like there is in the other one

**Comment by daemel** [comment]
I have these fixes planned, will work on them today along with the others.

**Comment by kamoclav** [comment]
@v-pbartley  Critical Path
