### ISSUE TITLE
Images in Challenges are not showing up - rename to challenge 0# broke the links

### ISSUE THREAD

**Issue by kamoclav** [microsoft/openhack-mc4h#70]
Updating our challenge names to have zero broke some stuff . In Challenge 2 for example the images are pointing to the wrong place and not rendering. It is the case for all the challenges.

**Comment by kamoclav** [comment]
Updated the issue to be more generic, not just challenge 2

**Comment by daemel** [comment]
Since we are putting images under media the reference simply has to change from: / to:

from:  (/Challenge-2/media/add_request.jpg)
to: (./media/add_request.jpg)

**Comment by kamoclav** [comment]
@v-pbartley  Critical Path
