### ISSUE TITLE
Stand in Issue to point to issue in FHIR Bulk Loader Documentation

### ISSUE THREAD

**Issue by kamoclav** [microsoft/openhack-mc4h#72]
https://github.com/microsoft/fhir-loader/issues/7

The Fhir Bulk Loader documentation has the wrong script in the documentation to deploy the fhir bulk loader.

**Comment by daemel** [comment]
I'll fix as I add the script_dir variable to each deployment script.

**Comment by kamoclav** [comment]
@v-pbartley  Critical Path

**Comment by daemel** [comment]
linked to https://github.com/microsoft/fhir-loader/pull/8
