### ISSUE TITLE
Challenge 4 - Minor formatting inconsistency 

### ISSUE THREAD

**Issue by kamoclav** [microsoft/openhack-mc4h#73]
Challenge 4 has "Challenge -" at the beginning of each of the headers. No other challenges are formatted like that. Very minor but we should make it Step1, Step 2 etc to keep a consistent look and feel.

**Comment by daemel** [comment]
Thanks @kamoclav - I wrote 4 as more of a learning experience vs a challenge experience, hence the difference.  will re-do this to match the format and introduce challenges.

**Comment by kamoclav** [comment]
@daemel I can take this one when I do some other reformatting tomorrow
