### ISSUE TITLE
Bulk Loader failed zips moved to zipprocessed rather than ziperror

### ISSUE THREAD

**Issue by kamoclav** [microsoft/openhack-mc4h#75]
The FHIR bulk loader documentation says when a file is added to the appropriate container it will be moved to a container with the file type and processed or error based on the outcome. When I uploaded a zip of bundles the zip was moved to zipprocessed making it appear successful but every bundle received a 500 error.

![image](https://user-images.githubusercontent.com/78386846/144097477-5c376113-7fe6-44d9-933f-cb258bc1fa9e.png)

![image](https://user-images.githubusercontent.com/78386846/144098122-261523a6-0c75-4844-b464-d164aca31e88.png)

**Comment by daemel** [comment]
linked to https://github.com/microsoft/fhir-loader/pull/8
