### ISSUE TITLE
Bulk Loader deploy is not handling keyvault setup correctly when using proxy

### ISSUE THREAD

**Issue by kamoclav** [microsoft/openhack-mc4h#76]
I'm low on details for this one. I've tried to troubleshoot what is happening and this is as far as I could get. The bulk loader deployed correctly and I put a zip in the zip container, it processed and moved to zipprocessed. All the bundles failed and it looks like it's failing when it tries to use the keyvault. Since the keyvault setup is part of the deployment script (it asked for one and I provided it) it seems like something is not functioning as expected in the deployment script. I included my deployment script to show what inputs I used.

If you do not use Proxy it works fine

![image](https://user-images.githubusercontent.com/78386846/144131940-f0f7b2d3-86e8-4bdd-9ec1-4fe730d0dc7d.png)

![image](https://user-images.githubusercontent.com/78386846/144132216-b5fa2b67-caf5-420e-8ef4-7984c3e9fd87.png)

**Comment by kamoclav** [comment]
@v-pbartley  Critical Path

**Comment by daemel** [comment]
linked to PR request https://github.com/microsoft/fhir-loader/pull/8
